/*
 * XXX generated by the Mike stub compiler, should be machine generated.
 */

#ifdef USENRPC

/*
 * If we use a "generic" server-side stub that always copies a complete
 * reply message back into registers we need to save even the unused message
 * callee-save registers (r5-r12) here.
 */
#define GENSRVSTUB

#define EXPORT_BOOLEAN
#include <mach/boolean.h>
#include <mach/kern_return.h>
#include <mach/message.h>
#include <mach/rpc.h>
#include <mach/notify.h>
#include <mach/mach_types.h>
#include <mach/mig_errors.h>
#include <mach/mig_support.h>
#include <mach/msg_type.h>

#ifndef	mig_internal
#define	mig_internal	static
#endif

#ifndef	mig_external
#define mig_external
#endif

/* Routine _task_set_emulation */
mig_external kern_return_t task_set_emulation(
	mach_port_t target_port,
	vm_address_t routine_entry_pt,
	int routine_number)
{
	register int _rv __asm("r28");
	register int _arg0 __asm("r26");
	register int _arg1 __asm("r25");
	register int _arg2 __asm("r24");
	register int _arg3 __asm("r23");
	register int _param0 __asm("r5");
	register int _param1 __asm("r6");
	register int _param2 __asm("r7");
	register int _param3 __asm("r8");
	register int _param4 __asm("r9");
	register int _param5 __asm("r10");
	register int _param6 __asm("r11");
	register int _param7 __asm("r12");
	register int _portname __asm("r13");
	register int _porttype __asm("r14");
	register int _memaddr __asm("r15");
	register int _memsize __asm("r16");

	_arg0 = target_port;
	_arg1 = 0x800;
	_arg2 = 0;
	_param0 = routine_entry_pt;
	_param1 = routine_number;
	_portname = 0;
	_memaddr = 0;
	__asm __volatile("
	" : 
	  : "r" (_param0), "r" (_param1), "r" (_portname), "r" (_memaddr));
#ifdef GENSRVSTUB
	__asm __volatile("
	" :
	  : "r" (_param2), "r" (_param3), "r" (_param4), "r" (_param5), "r" (_param6), "r" (_param7), "r" (_porttype), "r" (_memsize));
#endif
	__asm __volatile("
		ble	0x014(%%sr7,%0)
		ldo	0x16(%2),%2
	" : 
	  : "r" (0xc0000000), "r" (_arg0), "r" (_arg1), "r" (_arg2)
	  : "r1", "r19", "r20", "r21", "r22", "r23", "r24", "r25", "r26", "r28", "r29", "r31", "SAR", "memory");
	__asm __volatile("
	" :  "=r" (_param0));

#ifdef PARANOIA
	if (_arg1 != 2170)
		return 1;
#endif
	if (_rv == 0)
		_rv = _param0;
	return _rv;
}
#endif
