/* 
 * Copyright (c) 1995, The University of Utah and
 * the Computer Systems Laboratory at the University of Utah (CSL).
 * All rights reserved.
 *
 * Permission to use, copy, modify and distribute this software is hereby
 * granted provided that (1) source code retains these copyright, permission,
 * and disclaimer notices, and (2) redistributions including binaries
 * reproduce the notices in supporting documentation, and (3) all advertising
 * materials mentioning features or use of this software display the following
 * acknowledgement: ``This product includes software developed by the
 * Computer Systems Laboratory at the University of Utah.''
 *
 * THE UNIVERSITY OF UTAH AND CSL ALLOW FREE USE OF THIS SOFTWARE IN ITS "AS
 * IS" CONDITION.  THE UNIVERSITY OF UTAH AND CSL DISCLAIM ANY LIABILITY OF
 * ANY KIND FOR ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
 *
 * CSL requests users of this software to return to csl-dist@cs.utah.edu any
 * improvements that they make and grant CSL redistribution rights.
 *
 * 	Utah $Hdr: Nbsd_1_user.c 1.1 95/08/23$
 */

/*
 * XXX temporary XXX
 *
 * This file was actually generated by flick.
 */
#ifdef USENRPC
#include <mach/machine/flick_mach4_cstub.h>

unsigned int bsd_execve(mom_ref_t _req_port, signed int arg_addr, signed int arg_size, signed int arg_count, signed int env_count, unsigned char *fname, signed int fnameCnt)
{
  long _paramsave[11];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _param5;
  _paramsave[6] = _param6;
  _paramsave[7] = _portsnd;
  _paramsave[8] = _porttype;
  _paramsave[9] = _bufsend;
  _paramsave[10] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101000;
    _param2 = arg_addr;
    _param3 = arg_size;
    _param4 = arg_count;
    _param5 = env_count;
    _param6 = fnameCnt;
    flick_mach4_encode_one_block(fname,fnameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )fname;
  _bufscnt = fnameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_param4),
     "r" (_param5),
     "r" (_param6),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t37_discrim;
      mom_signed32_t _t38_discrim;

      _t37_discrim = _param0;
      _t38_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _param5 = _paramsave[5];
  _param6 = _paramsave[6];
  _portsnd = _paramsave[7];
  _porttype = _paramsave[8];
  _bufsend = _paramsave[9];
  _bufscnt = _paramsave[10];
  return _return;
}

unsigned int bsd_after_exec(mom_ref_t _req_port, signed int *arg_addr, signed int *arg_size, signed int *arg_count, signed int *env_count, mom_ref_t *image_port, unsigned char *emul_name, signed int *emul_nameCnt, unsigned char *fname, signed int *fnameCnt, unsigned char *cfname, signed int *cfnameCnt, unsigned char *cfarg, signed int *cfargCnt)
{
  long _recvbuffer[1027];
  int _recviter = 0;
  long _paramsave[12];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _param5;
  _paramsave[6] = _param6;
  _paramsave[7] = _param7;
  _paramsave[8] = _portsnd;
  _paramsave[9] = _porttype;
  _paramsave[10] = _bufsend;
  _paramsave[11] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101001;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = (unsigned long) _recvbuffer;
  _bufrcnt = 4108;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3)  ,
  "=r" (_param4)  ,
  "=r" (_param5)  ,
  "=r" (_param6)  ,
  "=r" (_param7));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret)  ,
  "=r" (_portsnd)  ,
  "=r" (_porttype)  ,
  "=r" (_bufrecv)  ,
  "=r" (_bufrcnt));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t39_discrim;
      mom_signed32_t _t40_discrim;

      _t39_discrim = _param0;
      _t40_discrim = _param1;
      _return = _param2;
      *arg_addr = _param3;
      *arg_size = _param4;
      *arg_count = _param5;
      *env_count = _param6;
      *image_port = (mom_ref_t )_portsnd;
      *emul_nameCnt = _param7;
      flick_mach4_decode_block(emul_name,*emul_nameCnt * sizeof(unsigned char ),1024);
      flick_mach4_decode_int(*fnameCnt);
      flick_mach4_decode_block(fname,*fnameCnt * sizeof(unsigned char ),1024);
      flick_mach4_decode_int(*cfnameCnt);
      flick_mach4_decode_block(cfname,*cfnameCnt * sizeof(unsigned char ),1024);
      flick_mach4_decode_int(*cfargCnt);
      flick_mach4_decode_block(cfarg,*cfargCnt * sizeof(unsigned char ),1024);
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _param5 = _paramsave[5];
  _param6 = _paramsave[6];
  _param7 = _paramsave[7];
  _portsnd = _paramsave[8];
  _porttype = _paramsave[9];
  _bufsend = _paramsave[10];
  _bufscnt = _paramsave[11];
  return _return;
}

unsigned int bsd_vm_map(mom_ref_t _req_port, signed int *address, signed int size, signed int mask, signed int anywhere, mom_ref_t memory_object_representative, signed int offset, signed int copy, signed int cur_protection, signed int max_protection, signed int inheritance)
{
  long _sendbuffer[3];
  int _senditer = 0;
  long _paramsave[12];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _param5;
  _paramsave[6] = _param6;
  _paramsave[7] = _param7;
  _paramsave[8] = _portsnd;
  _paramsave[9] = _porttype;
  _paramsave[10] = _bufsend;
  _paramsave[11] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101002;
    _param2 = *address;
    _param3 = size;
    _param4 = mask;
    _param5 = anywhere;
    _porttype = 19;
    _portsnd = (mom_ref_t )memory_object_representative;
    _param6 = offset;
    _param7 = copy;
    flick_mach4_encode_int(cur_protection);
    flick_mach4_encode_int(max_protection);
    flick_mach4_encode_int(inheritance);
  }
  _portrec = (unsigned long) _req_port;
  _bufsend = (unsigned long) _sendbuffer;
  _bufscnt = 12;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_param4),
     "r" (_param5),
     "r" (_param6),
     "r" (_param7),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t41_discrim;
      mom_signed32_t _t42_discrim;

      _t41_discrim = _param0;
      _t42_discrim = _param1;
      _return = _param2;
      *address = _param3;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _param5 = _paramsave[5];
  _param6 = _paramsave[6];
  _param7 = _paramsave[7];
  _portsnd = _paramsave[8];
  _porttype = _paramsave[9];
  _bufsend = _paramsave[10];
  _bufscnt = _paramsave[11];
  return _return;
}

unsigned int bsd_fd_to_file_port(mom_ref_t _req_port, signed int fileno, mom_ref_t *port)
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101003;
    _param2 = fileno;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret)  ,
  "=r" (_portsnd)  ,
  "=r" (_porttype));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t43_discrim;
      mom_signed32_t _t44_discrim;

      _t43_discrim = _param0;
      _t44_discrim = _param1;
      _return = _param2;
      *port = (mom_ref_t )_portsnd;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_file_port_open(mom_ref_t _req_port, signed int mode, signed int crtmode, unsigned char *fname, signed int fnameCnt, mom_ref_t *port)
{
  long _paramsave[9];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _portsnd;
  _paramsave[6] = _porttype;
  _paramsave[7] = _bufsend;
  _paramsave[8] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101004;
    _param2 = mode;
    _param3 = crtmode;
    _param4 = fnameCnt;
    flick_mach4_encode_one_block(fname,fnameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )fname;
  _bufscnt = fnameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_param4),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret)  ,
  "=r" (_portsnd)  ,
  "=r" (_porttype));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t45_discrim;
      mom_signed32_t _t46_discrim;

      _t45_discrim = _param0;
      _t46_discrim = _param1;
      _return = _param2;
      *port = (mom_ref_t )_portsnd;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _portsnd = _paramsave[5];
  _porttype = _paramsave[6];
  _bufsend = _paramsave[7];
  _bufscnt = _paramsave[8];
  return _return;
}

unsigned int bsd_signal_port_register(mom_ref_t _req_port, mom_ref_t sigport)
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101006;
    _porttype = 20;
    _portsnd = (mom_ref_t )sigport;
  }
  _portrec = (unsigned long) _req_port;
  _bufsend = 0;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t47_discrim;
      mom_signed32_t _t48_discrim;

      _t47_discrim = _param0;
      _t48_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_fork(mom_ref_t _req_port, signed int *new_state, signed int new_stateCnt, signed int *child_pid)
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101007;
    _param2 = new_stateCnt;
    flick_mach4_encode_one_block(new_state,new_stateCnt * sizeof(signed int ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )new_state;
  _bufscnt = new_stateCnt * sizeof(signed int );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t49_discrim;
      mom_signed32_t _t50_discrim;

      _t49_discrim = _param0;
      _t50_discrim = _param1;
      _return = _param2;
      *child_pid = _param3;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_vfork(mom_ref_t _req_port, signed int *new_state, signed int new_stateCnt, signed int *child_pid)
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101008;
    _param2 = new_stateCnt;
    flick_mach4_encode_one_block(new_state,new_stateCnt * sizeof(signed int ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )new_state;
  _bufscnt = new_stateCnt * sizeof(signed int );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t51_discrim;
      mom_signed32_t _t52_discrim;

      _t51_discrim = _param0;
      _t52_discrim = _param1;
      _return = _param2;
      *child_pid = _param3;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_take_signal(mom_ref_t _req_port, signed int *old_mask, signed int *old_onstack, signed int *sig, signed int *code, signed int *handler, signed int *new_sp)
{
  long _recvbuffer[1];
  int _recviter = 0;
  long _paramsave[12];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _param5;
  _paramsave[6] = _param6;
  _paramsave[7] = _param7;
  _paramsave[8] = _portsnd;
  _paramsave[9] = _porttype;
  _paramsave[10] = _bufsend;
  _paramsave[11] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101009;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = (unsigned long) _recvbuffer;
  _bufrcnt = 4;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3)  ,
  "=r" (_param4)  ,
  "=r" (_param5)  ,
  "=r" (_param6)  ,
  "=r" (_param7));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret)  ,
  "=r" (_bufrecv)  ,
  "=r" (_bufrcnt));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t53_discrim;
      mom_signed32_t _t54_discrim;

      _t53_discrim = _param0;
      _t54_discrim = _param1;
      _return = _param2;
      *old_mask = _param3;
      *old_onstack = _param4;
      *sig = _param5;
      *code = _param6;
      *handler = _param7;
      flick_mach4_decode_int(*new_sp);
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _param5 = _paramsave[5];
  _param6 = _paramsave[6];
  _param7 = _paramsave[7];
  _portsnd = _paramsave[8];
  _porttype = _paramsave[9];
  _bufsend = _paramsave[10];
  _bufscnt = _paramsave[11];
  return _return;
}

unsigned int bsd_sigreturn(mom_ref_t _req_port, signed int old_on_stack, signed int old_sigmask)
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101010;
    _param2 = old_on_stack;
    _param3 = old_sigmask;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t55_discrim;
      mom_signed32_t _t56_discrim;

      _t55_discrim = _param0;
      _t56_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_getrusage(mom_ref_t _req_port, signed int which, signed int rusage[18])
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101011;
    _param2 = which;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = (unsigned int )rusage;
  _bufrcnt = 18 * sizeof(signed int );
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret)  ,
  "=r" (_bufrecv)  ,
  "=r" (_bufrcnt));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t57_discrim;
      mom_signed32_t _t58_discrim;
      mom_unsigned8_t _t59_array_length;

      _t57_discrim = _param0;
      _t58_discrim = _param1;
      _return = _param2;
      _t59_array_length = 18;
      flick_mach4_decode_one_block(rusage,_t59_array_length * sizeof(signed int ),18);
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_chdir(mom_ref_t _req_port, unsigned char *fname, signed int fnameCnt)
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101012;
    _param2 = fnameCnt;
    flick_mach4_encode_one_block(fname,fnameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )fname;
  _bufscnt = fnameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t60_discrim;
      mom_signed32_t _t61_discrim;

      _t60_discrim = _param0;
      _t61_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_chroot(mom_ref_t _req_port, unsigned char *fname, signed int fnameCnt)
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101013;
    _param2 = fnameCnt;
    flick_mach4_encode_one_block(fname,fnameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )fname;
  _bufscnt = fnameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t62_discrim;
      mom_signed32_t _t63_discrim;

      _t62_discrim = _param0;
      _t63_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_open(mom_ref_t _req_port, signed int mode, signed int crtmode, unsigned char *fname, signed int fnameCnt, signed int *fileno)
{
  long _paramsave[9];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _portsnd;
  _paramsave[6] = _porttype;
  _paramsave[7] = _bufsend;
  _paramsave[8] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101014;
    _param2 = mode;
    _param3 = crtmode;
    _param4 = fnameCnt;
    flick_mach4_encode_one_block(fname,fnameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )fname;
  _bufscnt = fnameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_param4),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t64_discrim;
      mom_signed32_t _t65_discrim;

      _t64_discrim = _param0;
      _t65_discrim = _param1;
      _return = _param2;
      *fileno = _param3;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _portsnd = _paramsave[5];
  _porttype = _paramsave[6];
  _bufsend = _paramsave[7];
  _bufscnt = _paramsave[8];
  return _return;
}

unsigned int bsd_mknod(mom_ref_t _req_port, signed int fmode, signed int dev, unsigned char *fname, signed int fnameCnt)
{
  long _paramsave[9];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _portsnd;
  _paramsave[6] = _porttype;
  _paramsave[7] = _bufsend;
  _paramsave[8] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101015;
    _param2 = fmode;
    _param3 = dev;
    _param4 = fnameCnt;
    flick_mach4_encode_one_block(fname,fnameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )fname;
  _bufscnt = fnameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_param4),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t66_discrim;
      mom_signed32_t _t67_discrim;

      _t66_discrim = _param0;
      _t67_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _portsnd = _paramsave[5];
  _porttype = _paramsave[6];
  _bufsend = _paramsave[7];
  _bufscnt = _paramsave[8];
  return _return;
}

unsigned int bsd_link(mom_ref_t _req_port, unsigned char *target, signed int targetCnt, unsigned char *linkname, signed int linknameCnt)
{
  long _sendbuffer[512];
  int _senditer = 0;
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101016;
    _param2 = targetCnt;
    flick_mach4_encode_block(target,targetCnt * sizeof(unsigned char ));
    _param3 = linknameCnt;
    flick_mach4_encode_block(linkname,linknameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned long) _sendbuffer;
  _bufscnt = 2048;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t68_discrim;
      mom_signed32_t _t69_discrim;

      _t68_discrim = _param0;
      _t69_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_symlink(mom_ref_t _req_port, unsigned char *target, signed int targetCnt, unsigned char *linkname, signed int linknameCnt)
{
  long _sendbuffer[512];
  int _senditer = 0;
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101017;
    _param2 = targetCnt;
    flick_mach4_encode_block(target,targetCnt * sizeof(unsigned char ));
    _param3 = linknameCnt;
    flick_mach4_encode_block(linkname,linknameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned long) _sendbuffer;
  _bufscnt = 2048;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t70_discrim;
      mom_signed32_t _t71_discrim;

      _t70_discrim = _param0;
      _t71_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_unlink(mom_ref_t _req_port, unsigned char *fname, signed int fnameCnt)
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101018;
    _param2 = fnameCnt;
    flick_mach4_encode_one_block(fname,fnameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )fname;
  _bufscnt = fnameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t72_discrim;
      mom_signed32_t _t73_discrim;

      _t72_discrim = _param0;
      _t73_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_access(mom_ref_t _req_port, signed int fmode, unsigned char *fname, signed int fnameCnt)
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101019;
    _param2 = fmode;
    _param3 = fnameCnt;
    flick_mach4_encode_one_block(fname,fnameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )fname;
  _bufscnt = fnameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t74_discrim;
      mom_signed32_t _t75_discrim;

      _t74_discrim = _param0;
      _t75_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_readlink(mom_ref_t _req_port, signed int count, unsigned char *name, signed int nameCnt, unsigned char *buf, signed int *bufCnt)
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101020;
    _param2 = count;
    _param3 = nameCnt;
    flick_mach4_encode_one_block(name,nameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )name;
  _bufscnt = nameCnt * sizeof(unsigned char );
  _bufrecv = (unsigned int )buf;
  _bufrcnt = *bufCnt * sizeof(unsigned char );
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret)  ,
  "=r" (_bufrecv)  ,
  "=r" (_bufrcnt));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t76_discrim;
      mom_signed32_t _t77_discrim;

      _t76_discrim = _param0;
      _t77_discrim = _param1;
      _return = _param2;
      *bufCnt = _param3;
      flick_mach4_decode_one_block(buf,*bufCnt * sizeof(unsigned char ),8192);
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_rename(mom_ref_t _req_port, unsigned char *from_name, signed int from_nameCnt, unsigned char *to_name, signed int to_nameCnt)
{
  long _sendbuffer[512];
  int _senditer = 0;
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101022;
    _param2 = from_nameCnt;
    flick_mach4_encode_block(from_name,from_nameCnt * sizeof(unsigned char ));
    _param3 = to_nameCnt;
    flick_mach4_encode_block(to_name,to_nameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned long) _sendbuffer;
  _bufscnt = 2048;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t78_discrim;
      mom_signed32_t _t79_discrim;

      _t78_discrim = _param0;
      _t79_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_mkdir(mom_ref_t _req_port, signed int dmode, unsigned char *name, signed int nameCnt)
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101023;
    _param2 = dmode;
    _param3 = nameCnt;
    flick_mach4_encode_one_block(name,nameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )name;
  _bufscnt = nameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t80_discrim;
      mom_signed32_t _t81_discrim;

      _t80_discrim = _param0;
      _t81_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_rmdir(mom_ref_t _req_port, unsigned char *name, signed int nameCnt)
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101024;
    _param2 = nameCnt;
    flick_mach4_encode_one_block(name,nameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )name;
  _bufscnt = nameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t82_discrim;
      mom_signed32_t _t83_discrim;

      _t82_discrim = _param0;
      _t83_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_acct(mom_ref_t _req_port, signed int acct_on, unsigned char *fname, signed int fnameCnt)
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101025;
    _param2 = acct_on;
    _param3 = fnameCnt;
    flick_mach4_encode_one_block(fname,fnameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )fname;
  _bufscnt = fnameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t84_discrim;
      mom_signed32_t _t85_discrim;

      _t84_discrim = _param0;
      _t85_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_write_short(mom_ref_t _req_port, signed int fileno, unsigned char *data, signed int dataCnt, signed int *amount_written)
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101026;
    _param2 = fileno;
    _param3 = dataCnt;
    flick_mach4_encode_one_block(data,dataCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )data;
  _bufscnt = dataCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t86_discrim;
      mom_signed32_t _t87_discrim;

      _t86_discrim = _param0;
      _t87_discrim = _param1;
      _return = _param2;
      *amount_written = _param3;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_read_short(mom_ref_t _req_port, signed int fileno, signed int datalen, signed int *nread, unsigned char *data, signed int *dataCnt)
{
  long _paramsave[9];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _portsnd;
  _paramsave[6] = _porttype;
  _paramsave[7] = _bufsend;
  _paramsave[8] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101028;
    _param2 = fileno;
    _param3 = datalen;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = (unsigned int )data;
  _bufrcnt = *dataCnt * sizeof(unsigned char );
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3)  ,
  "=r" (_param4));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret)  ,
  "=r" (_bufrecv)  ,
  "=r" (_bufrcnt));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t88_discrim;
      mom_signed32_t _t89_discrim;

      _t88_discrim = _param0;
      _t89_discrim = _param1;
      _return = _param2;
      *nread = _param3;
      *dataCnt = _param4;
      flick_mach4_decode_one_block(data,*dataCnt * sizeof(unsigned char ),8192);
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _portsnd = _paramsave[5];
  _porttype = _paramsave[6];
  _bufsend = _paramsave[7];
  _bufscnt = _paramsave[8];
  return _return;
}

unsigned int bsd_setgroups(mom_ref_t _req_port, signed int gidsetsize, signed int gidset[16])
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    mom_unsigned8_t _t90_array_length;

    _param0 = 5065031;
    _param1 = 101036;
    _param2 = gidsetsize;
    _t90_array_length = 16;
    flick_mach4_encode_one_block(gidset,_t90_array_length * sizeof(signed int ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )gidset;
  _bufscnt = 16 * sizeof(signed int );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t91_discrim;
      mom_signed32_t _t92_discrim;

      _t91_discrim = _param0;
      _t92_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_setrlimit(mom_ref_t _req_port, signed int which, signed int lim[4])
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    mom_unsigned8_t _t93_array_length;

    _param0 = 5065031;
    _param1 = 101037;
    _param2 = which;
    _t93_array_length = 4;
    flick_mach4_encode_one_block(lim,_t93_array_length * sizeof(signed int ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )lim;
  _bufscnt = 4 * sizeof(signed int );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t94_discrim;
      mom_signed32_t _t95_discrim;

      _t94_discrim = _param0;
      _t95_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_bind(mom_ref_t _req_port, signed int s, unsigned char *name, signed int nameCnt)
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101044;
    _param2 = s;
    _param3 = nameCnt;
    flick_mach4_encode_one_block(name,nameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )name;
  _bufscnt = nameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t96_discrim;
      mom_signed32_t _t97_discrim;

      _t96_discrim = _param0;
      _t97_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_connect(mom_ref_t _req_port, signed int s, unsigned char *name, signed int nameCnt)
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101046;
    _param2 = s;
    _param3 = nameCnt;
    flick_mach4_encode_one_block(name,nameCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )name;
  _bufscnt = nameCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t98_discrim;
      mom_signed32_t _t99_discrim;

      _t98_discrim = _param0;
      _t99_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_setsockopt(mom_ref_t _req_port, signed int s, signed int level, signed int name, unsigned char *val, signed int valCnt)
{
  long _paramsave[10];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _param5;
  _paramsave[6] = _portsnd;
  _paramsave[7] = _porttype;
  _paramsave[8] = _bufsend;
  _paramsave[9] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101047;
    _param2 = s;
    _param3 = level;
    _param4 = name;
    _param5 = valCnt;
    flick_mach4_encode_one_block(val,valCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )val;
  _bufscnt = valCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_param4),
     "r" (_param5),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t100_discrim;
      mom_signed32_t _t101_discrim;

      _t100_discrim = _param0;
      _t101_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _param5 = _paramsave[5];
  _portsnd = _paramsave[6];
  _porttype = _paramsave[7];
  _bufsend = _paramsave[8];
  _bufscnt = _paramsave[9];
  return _return;
}

unsigned int bsd_getsockopt(mom_ref_t _req_port, signed int s, signed int level, signed int name, unsigned char *val, signed int *valCnt)
{
  long _paramsave[9];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _portsnd;
  _paramsave[6] = _porttype;
  _paramsave[7] = _bufsend;
  _paramsave[8] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101048;
    _param2 = s;
    _param3 = level;
    _param4 = name;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = (unsigned int )val;
  _bufrcnt = *valCnt * sizeof(unsigned char );
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_param4),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret)  ,
  "=r" (_bufrecv)  ,
  "=r" (_bufrcnt));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t102_discrim;
      mom_signed32_t _t103_discrim;

      _t102_discrim = _param0;
      _t103_discrim = _param1;
      _return = _param2;
      *valCnt = _param3;
      flick_mach4_decode_one_block(val,*valCnt * sizeof(unsigned char ),128);
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _portsnd = _paramsave[5];
  _porttype = _paramsave[6];
  _bufsend = _paramsave[7];
  _bufscnt = _paramsave[8];
  return _return;
}

unsigned int bsd_init_process(mom_ref_t _req_port)
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101051;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t104_discrim;
      mom_signed32_t _t105_discrim;

      _t104_discrim = _param0;
      _t105_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_table_set(mom_ref_t _req_port, signed int id, signed int index, signed int lel, signed int nel, unsigned char *addr, signed int addrCnt, signed int *nel_done)
{
  long _paramsave[11];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _param5;
  _paramsave[6] = _param6;
  _paramsave[7] = _portsnd;
  _paramsave[8] = _porttype;
  _paramsave[9] = _bufsend;
  _paramsave[10] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101052;
    _param2 = id;
    _param3 = index;
    _param4 = lel;
    _param5 = nel;
    _param6 = addrCnt;
    flick_mach4_encode_one_block(addr,addrCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )addr;
  _bufscnt = addrCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_param4),
     "r" (_param5),
     "r" (_param6),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t106_discrim;
      mom_signed32_t _t107_discrim;

      _t106_discrim = _param0;
      _t107_discrim = _param1;
      _return = _param2;
      *nel_done = _param3;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _param5 = _paramsave[5];
  _param6 = _paramsave[6];
  _portsnd = _paramsave[7];
  _porttype = _paramsave[8];
  _bufsend = _paramsave[9];
  _bufscnt = _paramsave[10];
  return _return;
}

unsigned int bsd_emulator_error(mom_ref_t _req_port, unsigned char *err_message, signed int err_messageCnt)
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101054;
    _param2 = err_messageCnt;
    flick_mach4_encode_one_block(err_message,err_messageCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )err_message;
  _bufscnt = err_messageCnt * sizeof(unsigned char );
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t108_discrim;
      mom_signed32_t _t109_discrim;

      _t108_discrim = _param0;
      _t109_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_share_wakeup(mom_ref_t _req_port, signed int lock_offset)
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101056;
    _param2 = lock_offset;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t110_discrim;
      mom_signed32_t _t111_discrim;

      _t110_discrim = _param0;
      _t111_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_maprw_request_it(mom_ref_t _req_port, signed int fileno)
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101057;
    _param2 = fileno;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t112_discrim;
      mom_signed32_t _t113_discrim;

      _t112_discrim = _param0;
      _t113_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_maprw_release_it(mom_ref_t _req_port, signed int fileno)
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101058;
    _param2 = fileno;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t114_discrim;
      mom_signed32_t _t115_discrim;

      _t114_discrim = _param0;
      _t115_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_maprw_remap(mom_ref_t _req_port, signed int fileno, signed int offset, signed int size)
{
  long _paramsave[9];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _portsnd;
  _paramsave[6] = _porttype;
  _paramsave[7] = _bufsend;
  _paramsave[8] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101059;
    _param2 = fileno;
    _param3 = offset;
    _param4 = size;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_param4),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t116_discrim;
      mom_signed32_t _t117_discrim;

      _t116_discrim = _param0;
      _t117_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _portsnd = _paramsave[5];
  _porttype = _paramsave[6];
  _bufsend = _paramsave[7];
  _bufscnt = _paramsave[8];
  return _return;
}

#if 0
unsigned int bsd_mon_switch(mom_ref_t _req_port, signed int *sample_flavor)
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101061;
    _param2 = *sample_flavor;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t118_discrim;
      mom_signed32_t _t119_discrim;

      _t118_discrim = _param0;
      _t119_discrim = _param1;
      _return = _param2;
      *sample_flavor = _param3;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}
#endif

unsigned int bsd_getattr(mom_ref_t _req_port, signed int fileno, signed int vattr[24])
{
  long _paramsave[7];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _portsnd;
  _paramsave[4] = _porttype;
  _paramsave[5] = _bufsend;
  _paramsave[6] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101063;
    _param2 = fileno;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = (unsigned int )vattr;
  _bufrcnt = 24 * sizeof(signed int );
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret)  ,
  "=r" (_bufrecv)  ,
  "=r" (_bufrcnt));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t120_discrim;
      mom_signed32_t _t121_discrim;
      mom_unsigned8_t _t122_array_length;

      _t120_discrim = _param0;
      _t121_discrim = _param1;
      _return = _param2;
      _t122_array_length = 24;
      flick_mach4_decode_one_block(vattr,_t122_array_length * sizeof(signed int ),24);
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _portsnd = _paramsave[3];
  _porttype = _paramsave[4];
  _bufsend = _paramsave[5];
  _bufscnt = _paramsave[6];
  return _return;
}

unsigned int bsd_path_getattr(mom_ref_t _req_port, signed int follow, unsigned char *path, signed int pathCnt, signed int vattr[24])
{
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101065;
    _param2 = follow;
    _param3 = pathCnt;
    flick_mach4_encode_one_block(path,pathCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned int )path;
  _bufscnt = pathCnt * sizeof(unsigned char );
  _bufrecv = (unsigned int )vattr;
  _bufrcnt = 24 * sizeof(signed int );
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret)  ,
  "=r" (_bufrecv)  ,
  "=r" (_bufrcnt));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t123_discrim;
      mom_signed32_t _t124_discrim;
      mom_unsigned8_t _t125_array_length;

      _t123_discrim = _param0;
      _t124_discrim = _param1;
      _return = _param2;
      _t125_array_length = 24;
      flick_mach4_decode_one_block(vattr,_t125_array_length * sizeof(signed int ),24);
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_set_atexpansion(mom_ref_t _req_port, unsigned char *what_to_expand, signed int what_to_expandCnt, unsigned char *expansion, signed int expansionCnt)
{
  long _sendbuffer[512];
  int _senditer = 0;
  long _paramsave[8];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _portsnd;
  _paramsave[5] = _porttype;
  _paramsave[6] = _bufsend;
  _paramsave[7] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101068;
    _param2 = what_to_expandCnt;
    flick_mach4_encode_block(what_to_expand,what_to_expandCnt * sizeof(unsigned char ));
    _param3 = expansionCnt;
    flick_mach4_encode_block(expansion,expansionCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned long) _sendbuffer;
  _bufscnt = 2048;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t126_discrim;
      mom_signed32_t _t127_discrim;

      _t126_discrim = _param0;
      _t127_discrim = _param1;
      _return = _param2;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _portsnd = _paramsave[4];
  _porttype = _paramsave[5];
  _bufsend = _paramsave[6];
  _bufscnt = _paramsave[7];
  return _return;
}

unsigned int bsd_sendmsg_short(mom_ref_t _req_port, signed int fileno, signed int flags, unsigned char *data, signed int dataCnt, unsigned char *to, signed int toCnt, unsigned char *cmsg, signed int cmsgCnt, signed int *nsent)
{
  long _sendbuffer[2112];
  int _senditer = 0;
  long _paramsave[11];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _param5;
  _paramsave[6] = _param6;
  _paramsave[7] = _portsnd;
  _paramsave[8] = _porttype;
  _paramsave[9] = _bufsend;
  _paramsave[10] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101069;
    _param2 = fileno;
    _param3 = flags;
    _param4 = dataCnt;
    flick_mach4_encode_block(data,dataCnt * sizeof(unsigned char ));
    _param5 = toCnt;
    flick_mach4_encode_block(to,toCnt * sizeof(unsigned char ));
    _param6 = cmsgCnt;
    flick_mach4_encode_block(cmsg,cmsgCnt * sizeof(unsigned char ));
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = (unsigned long) _sendbuffer;
  _bufscnt = 8448;
  _bufrecv = 0;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_param4),
     "r" (_param5),
     "r" (_param6),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t128_discrim;
      mom_signed32_t _t129_discrim;

      _t128_discrim = _param0;
      _t129_discrim = _param1;
      _return = _param2;
      *nsent = _param3;
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _param5 = _paramsave[5];
  _param6 = _paramsave[6];
  _portsnd = _paramsave[7];
  _porttype = _paramsave[8];
  _bufsend = _paramsave[9];
  _bufscnt = _paramsave[10];
  return _return;
}

unsigned int bsd_recvmsg_short(mom_ref_t _req_port, signed int fileno, signed int flags, signed int *outflags, signed int fromlen, signed int *nreceived, unsigned char *from, signed int *fromCnt, signed int cmsglen, unsigned char *cmsg, signed int *cmsgCnt, signed int datalen, unsigned char *data, signed int *dataCnt)
{
  long _recvbuffer[2112];
  int _recviter = 0;
  long _paramsave[12];
  unsigned int _return;

  _paramsave[0] = _param0;
  _paramsave[1] = _param1;
  _paramsave[2] = _param2;
  _paramsave[3] = _param3;
  _paramsave[4] = _param4;
  _paramsave[5] = _param5;
  _paramsave[6] = _param6;
  _paramsave[7] = _param7;
  _paramsave[8] = _portsnd;
  _paramsave[9] = _porttype;
  _paramsave[10] = _bufsend;
  _paramsave[11] = _bufscnt;
  {
    _param0 = 5065031;
    _param1 = 101071;
    _param2 = fileno;
    _param3 = flags;
    _param4 = fromlen;
    _param5 = cmsglen;
    _param6 = datalen;
  }
  _portrec = (unsigned long) _req_port;
  _portsnd = 0;
  _bufsend = 0;
  _bufrecv = (unsigned long) _recvbuffer;
  _bufrcnt = 8448;
  __asm __volatile("
  " :
    :     "r" (_param0),
     "r" (_param1),
     "r" (_param2),
     "r" (_param3),
     "r" (_param4),
     "r" (_param5),
     "r" (_param6),
     "r" (_msg_id));
  __asm __volatile("
  " :
    :     "r" (_portrec),
     "r" (_portsnd),
     "r" (_porttype),
     "r" (_bufrecv),
     "r" (_bufrcnt),
     "r" (_bufsend),
     "r" (_bufscnt));

  __asm __volatile("
    ble	0x014(%%sr7,%0)
    nop
  " :
    : "r" (0xc0000000), "r" (_portrec), "r" (_msg_id), "r" (_bufrecv)
    : "r1",
      "r19",
      "r20",
      "r21",
      "r22",
      "r23",
      "r24",
      "r25",
      "r26",
      "r27",
      "r28",
      "r29",
      "r30",
      "r31",
      "SAR",
      "memory");

  __asm __volatile("
  " :
    "=r" (_param0)  ,
  "=r" (_param0)  ,
  "=r" (_param1)  ,
  "=r" (_param2)  ,
  "=r" (_param3)  ,
  "=r" (_param4)  ,
  "=r" (_param5)  ,
  "=r" (_param6)  ,
  "=r" (_param7));

  __asm __volatile("
  " :
    "=r" (_msg_id)  ,
  "=r" (_ret)  ,
  "=r" (_bufrecv)  ,
  "=r" (_bufrcnt));

  if (((_return = _ret) == 0))
    {
      mom_signed32_t _t130_discrim;
      mom_signed32_t _t131_discrim;

      _t130_discrim = _param0;
      _t131_discrim = _param1;
      _return = _param2;
      *outflags = _param3;
      *nreceived = _param4;
      *fromCnt = _param5;
      flick_mach4_decode_block(from,*fromCnt * sizeof(unsigned char ),128);
      *cmsgCnt = _param6;
      flick_mach4_decode_block(cmsg,*cmsgCnt * sizeof(unsigned char ),128);
      *dataCnt = _param7;
      flick_mach4_decode_block(data,*dataCnt * sizeof(unsigned char ),8192);
    }
  _param0 = _paramsave[0];
  _param1 = _paramsave[1];
  _param2 = _paramsave[2];
  _param3 = _paramsave[3];
  _param4 = _paramsave[4];
  _param5 = _paramsave[5];
  _param6 = _paramsave[6];
  _param7 = _paramsave[7];
  _portsnd = _paramsave[8];
  _porttype = _paramsave[9];
  _bufsend = _paramsave[10];
  _bufscnt = _paramsave[11];
  return _return;
}

#endif
